language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache:
  pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=coverage
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
script:
  - tox
