language: python
addons:
  firefox: "63.0.3"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=coverage
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - sudo tar -C /usr/local/bin/ -xvzf geckodriver*
  - sudo chmod +x /usr/local/bin/geckodriver
  - export PATH=$PATH:/usr/local/bin/
  - pip install tox tox-travis
script:
  - tox
notifications:
  email: false
