matrix:
  include:
    - language: python
      python: 
        - "2.7"
      install:
        - pip install -r requirements-dev.txt
        - pip install -r requirements.txt
      script:
        - tox
    - language: python
      python: 
        - "3.4"
      install:
        - pip install -r requirements-dev.txt
        - pip install -r requirements.txt
      script:
        - tox
    - language: python
      python: 
        - "3.5"
      install:
        - pip install -r requirements-dev.txt
        - pip install -r requirements.txt
      script:
        - tox
    - language: python
      python: 
        - "3.6"
      install:
        - pip install -r requirements-dev.txt
        - pip install -r requirements.txt
      script:
        - tox
    - language: node_js
      node_js:
        - 4.8
      before_install:
        - cd js
        - npm install
      install:
        - npm prepare
      script:
        - yarn test
    - language: python
      python: 
        - "2.7"
      install:
        - pip install -r requirements-dev.txt
        - pip install -r requirements.txt
      script:
        - tox -e flake8
    - language: python
      python: 
        - "3.6"
      install:
        - pip install -r requirements-dev.txt
        - pip install -r requirements.txt
      script:
        - tox -e coverage

notifications:
  email: false
