language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 2.7
      env: FLAKE8=YES COVERAGE=YES PYLINT=YES
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
script:
  - tox